export default {
    logo: require('../images/logo.png'),
    auth_background: require('../images/bg.jpg'),
    auth_background2: require('../images/auth_background2.png'),
    layer_img: require('../images/s1.png'),
    logo_shadow: require('../images/logo_shadow.png'),
    facebook: require('../images/facebook.png'),
    google: require('../images/google.png'),
    img_upload: require('../images/upload_img.png'),
    user1: require('../images/user1.png'),
    fire: require('../images/fire.png'),
    location: require('../images/location.png'),
    clock: require('../images/clock.png'),
    stars: require('../images/stars.png'),
    tscImg1: require('../images/tscImg1.png'),
    tscImg2: require('../images/tscImg2.png'),
    tscImg3: require('../images/tscImg3.png'),
    tscImg4: require('../images/tscImg4.png'),
    tscImg5: require('../images/tscImg5.png'),
    tscImg6: require('../images/tscImg6.png'),
    tscIcon1: require('../images/tscIcon1.png'),
    tscIcon2: require('../images/tscIcon2.png'),
    tscUser1: require('../images/tscUser1.png'),
    carImg1: require('../images/carImg1.png'),
    arrowUpLeft: require('../images/arrow-up-left.png'),
    Journey: require('../images/Journey.png'), 
    paginationIcon: require('../images/paginationIcon.png'), 
  };